import Head from 'next/head';
import IndexPage from '@/components/IndexPage';

export default function index() {
  return (
    <>
      <Head>
        <title>Rock Paper Scissors | Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/dice-3.svg" />
      </Head>
      <IndexPage/>
    </>
  )
}
